---
experiment_name: "CHB_federated_1"
Date: "11_09_24"

# Data settings
Dataset: "CHB_MIT"     # MNIST_NIID or MIT_BIH
n_clients: 23
n_clients_UCB: 23
seed: 42

# MNIST
n_classes_total: 4
n_classes_per_user: 4
# MIT-BIH 
data_fraction: 1
# AFPL 
alpha: 0.75
# IFCA 
k: 6

# Training settings
network: "Net"
n_epochs: 100
local_iterations: 1
type: "federated" # global, local or federated

# Display settings
calc_accuracy: "True" 
disp_loss: "True" 
log_interval: 25

# reproducibility 
save_models: "True"
