---
experiment_name: "MNIST_IFCL_5" 
Date: "30_06_2023"

# Data settings
Dataset: "MNIST"     # MNIST_NIID or MIT_BIH
n_clients: 100
n_clients_UCB: 1
seed: 46

# MNIST
n_classes_total: 4
n_classes_per_user: 2
# MIT-BIH 
data_fraction: 1
# AFPL 
alpha: 0.75
# IFCA 
k: 6

# Training settings
network: "Net"
n_epochs: 100
local_iterations: 1
type: "ifca" # global, local or federated

# Display settings
calc_accuracy: "True" 
disp_loss: "True" 
log_interval: 25

# reproducibility 
save_models: "True"
